### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by meokey** [dPhoeniixx/Textnow-API#11]
it has been working well until a few days ago. It start to raise error when executing TN.login().
Would you please have a look, and if possible, make the API Python3 compatible. Thanks.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "textnow.py", line 60, in login
    req = self.sendReq("POST", "%s%s%s"%(self.API_URL, node, query), sign, jsonData)
  File "textnow.py", line 34, in sendReq
    return requests.post(url, data={'json':str(data).replace("\\\\", "\\")}, headers={'User-Agent':self.USER_AGENT}).json()
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by buidoi8x** [comment]
Textnow has just updated API.
So this tool need to update.
Hope that admin will update soon
